In [2]:
import pandas as pd
df = pd.read_csv('data_for_large_scale.csv')
y = df['Target'].values
X = df.drop(['Target'], axis=1).values

In [3]:
X

array([[-1.58  ,  1.05  ,  1.06  , ...,  0.265 ,  0.268 , -0.851 ],
       [-0.832 , -0.866 , -1.34  , ...,  0.135 , -0.088 , -1.55  ],
       [-0.237 ,  2.09  , -3.93  , ..., -0.0287,  1.82  ,  0.938 ],
       ...,
       [ 0.509 , -0.322 ,  0.681 , ...,  0.727 , -1.94  , -2.01  ],
       [ 0.36  ,  1.25  ,  0.651 , ..., -0.367 , -1.28  , -1.1   ],
       [-0.86  , -0.601 ,  0.739 , ..., -0.483 , -1.38  ,  1.11  ]])

In [4]:
y

array([  84.7, -211. ,  -96.9, ...,  -80.2,  158. , -369. ])

In [15]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, random_state=10, train_size=63000)

In [16]:
xtrain.shape

(63000, 10)

In [17]:
ytrain.shape

(63000,)

In [18]:
xtest.shape

(27000, 10)

In [19]:
ytest.shape

(27000,)

In [10]:
from sklearn.linear_model import SGDRegressor

In [11]:
clf = SGDRegressor(random_state=10)

In [12]:
X.shape

(90000, 10)

In [21]:
import numpy as np

In [25]:
x_chunks = np.split(xtrain, 63000 / 90)
y_chunks = np.split(ytrain, 63000 / 90)

In [34]:
clf = SGDRegressor(random_state=10)
for i, (xx, yy) in enumerate(zip(x_chunks, y_chunks)):
    clf.partial_fit(xx, yy)
    if i == 4:
        print(clf.coef_[4])

56.05563939842212


---

In [35]:
from sklearn.preprocessing import StandardScaler

In [58]:
scaler = StandardScaler()
n_samples = 0

for df in pd.read_csv('3D_spatial_network.txt', header=None, names=['id', 'long', 'lat', 'alt'], chunksize=20000, iterator=True, index_col='id'):
    n_samples += df.shape[0]
    # scaler.partial_fit(df.values)
    


clf = SGDRegressor(random_state=10)
for i, df in enumerate(pd.read_csv('3D_spatial_network.txt', header=None, names=['id', 'long', 'lat', 'alt'], chunksize=20000, iterator=True, index_col='id')):
    #scaled = scaler.transform(df.values)
    # x = scaled[:, :-1]
    # y = scaled[:, -1]
    # x = scaler.transform(x)
    x = df.drop(['alt'], axis=1).values
    y = df['alt'].values
    clf.partial_fit(x, y)
    if i == 6:
        print(clf.intercept_)
        print(clf.coef_)

[1266649.4803808]
[  9189.18646607 -23769.10797827]


In [57]:
x.std(axis=0)

array([1.06046802, 1.05113236])

---

In [59]:
from sklearn.datasets import load_iris
from sklearn import neighbors as nn
iris = load_iris()

In [60]:
from sklearn.preprocessing import Normalizer

In [61]:
norm = Normalizer()
data = norm.fit_transform(iris.data)

In [62]:
xtrain, xtest, ytrain, ytest = train_test_split(data, iris.target, test_size=0.2, random_state=10)

In [63]:
for k in [2, 3, 4]:
    knn = nn.KNeighborsClassifier(n_neighbors=k)
    knn.fit(xtrain, ytrain)
    print(knn.score(xtest, ytest))

0.9666666666666667
0.9666666666666667
0.9666666666666667


In [64]:
knn = nn.KNeighborsClassifier(n_neighbors=3)
knn.fit(xtrain, ytrain)
y_pred = knn.predict(xtest)

In [65]:
from sklearn.metrics import f1_score

In [66]:
f1_score(ytest, y_pred, average='weighted')

0.9671111111111111