In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
cv = CountVectorizer()

In [3]:
text = text_data=[
    'A metaverse is a network of 3D virtual worlds focused on social connection.',
    'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
    'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
    'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
    'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
    'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
    'often including a significant interest in advancing virtual reality technology.', 
    'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
    'stemming from challenges facing the social media and video game industries as a whole.']

In [4]:
X = cv.fit_transform(text)

In [5]:
X.shape

(9, 99)

In [7]:
cv = CountVectorizer(min_df=2)
X = cv.fit_transform(text)
X.shape

(9, 20)

In [8]:
cv1 = CountVectorizer()
cv2 = CountVectorizer(min_df=2)

cv1.fit(text)
cv2.fit(text)

CountVectorizer(min_df=2)

In [10]:
cv2.vocabulary_

{'metaverse': 7,
 'is': 6,
 'of': 9,
 'virtual': 18,
 'social': 13,
 'in': 5,
 'and': 0,
 'science': 12,
 'fiction': 2,
 'the': 15,
 'term': 14,
 'often': 10,
 'as': 1,
 'world': 19,
 'use': 16,
 'reality': 11,
 'has': 4,
 'various': 17,
 'metaverses': 8,
 'for': 3}

In [11]:
docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]
cv1.fit_transform(docs).toarray()

array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1]])

In [13]:
import numpy as np

def k_closest(X, p, k):
    return

X = np.asarray([[72, 69 ,82],
                [ 9 ,79, 99],
                [20 ,47, 88],
                [80 ,64, 49]])
p = np.asarray([[0,0,0]])
k=1 

In [14]:
np.linalg.norm(X, axis=1)

array([129.10848152, 126.97637576, 101.74969287, 113.56495938])

In [15]:
from sklearn.neighbors import NearestNeighbors

In [21]:
nn = NearestNeighbors(n_neighbors=1)

In [23]:
nn.fit(X)

NearestNeighbors(n_neighbors=1)

In [25]:
nn.kneighbors(p, return_distance=False)

array([[2]])

In [27]:
X[[2]]

array([[20, 47, 88]])

In [28]:
def distance(x0, X, p=2):
    return np.sum(np.abs(X - x0) ** p, axis=1) ** (1 / p)

x0 = np.array([1,0,0,0])
X= np.asarray([
    [1, 0, 0,0],
    [0, 1, 1,1],
    [1,2,0,0]
])
distance(x0, X)

array([0., 2., 2.])

In [29]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [30]:
digits = load_digits()
xtrain, xtest, ytrain, ytest = train_test_split(digits.data, digits.target, test_size=0.2, random_state=10)

In [32]:
digits.data.shape

(1797, 64)

In [33]:
np.unique(digits.target).shape

(10,)

In [34]:
(digits.target == 7).sum()

179

In [35]:
scaler = StandardScaler()
x_tr = scaler.fit_transform(xtrain)
x_ts = scaler.transform(xtest)
lr = LogisticRegression(multi_class='multinomial', solver='sag')

In [36]:
lr.fit(x_tr, ytrain)

/home/jaidevd/conda/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,


LogisticRegression(multi_class='multinomial', solver='sag')

In [37]:
lr.score(x_ts, ytest)

0.9666666666666667

In [38]:
from sklearn.metrics import f1_score

In [40]:
f1_score(ytest, lr.predict(x_ts), average='weighted')

0.966907732026411